apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_USER: {{ .Values.env.dbUser | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
