apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbPassword: {{ .Values.secret.dbPassword | quote }}
